name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ls -la
      - run: cat requirements.txt

      - uses: PeterJCLaw/test-setup-python-1128@demo-action

      - run: ls -la
      - run: cat requirements.txt
